// Generated by scripts/generate_model_score_data.py; edit the JSON snapshot.
#pragma once

#include <array>
#include <optional>
#include <string_view>

namespace zed::app {

struct ModelBenchmarkRow {
  std::string_view id;
  std::array<std::optional<double>, 4> percentages;
  bool reference_mapping;
};

inline constexpr std::array<ModelBenchmarkRow, 26> kModelBenchmarkRows{{
    {"gpt-5.6-luna",
     {80.8988764044944, 93.0, std::nullopt, 53.587962962963},
     false},
    {"grok-4.6", {88.38951310861421, 95.6, 88.224, 56.4814814814815}, false},
    {"muse-spark-1.2-contributor",
     {80.1498127340824, 86.6, std::nullopt, 57.4074074074074},
     true},
    {"muse-spark-1.3-contributor",
     {85.76779026217231, std::nullopt, std::nullopt, 58.3333333333333},
     true},
    {"deepseek-v4-flash",
     {78.65168539325839, 88.8, 87.264, 50.3472222222222},
     true},
    {"deepseek-v4-flash-vision-exp",
     {74.1573033707865, std::nullopt, std::nullopt, 49.6527777777778},
     true},
    {"deepseek-v4-pro",
     {78.65168539325839, 96.4, 87.525, 51.0416666666667},
     true},
    {"glm-5.1", {61.797752808988804, 76.4, 81.38, std::nullopt}, false},
    {"glm-5.2", {77.9026217228464, 82.8, 69.5, 51.1574074074074}, false},
    {"glm-5.3", {83.8951310861423, 95.4, 80.535, 59.0277777777778}, false},
    {"glm-5.3-flash", {84.2696629213483, 92.0, 80.51, 51.6203703703704}, false},
    {"hy3",
     {64.4194756554307, std::nullopt, std::nullopt, 48.6111111111111},
     false},
    {"hy4-preview",
     {std::nullopt, std::nullopt, std::nullopt, std::nullopt},
     false},
    {"kimi-k2.6", {65.9176029962547, 76.2, 86.771, std::nullopt}, false},
    {"kimi-k2.7-code",
     {67.4157303370786, 78.2, 82.05, 47.8009259259259},
     false},
    {"kimi-k3", {85.0187265917603, 93.4, 87.185, 59.4907407407407}, false},
    {"longcat-2.0",
     {50.187265917603, std::nullopt, std::nullopt, 36.342592592592595},
     false},
    {"mimo-v2.5", {63.6704119850187, 71.0, 81.512, 43.8657407407407}, false},
    {"mimo-v2.5-pro",
     {65.1685393258427, 74.0, 81.354, 50.578703703703695},
     false},
    {"minimax-m2.7", {55.4307116104869, 73.8, 79.926, std::nullopt}, false},
    {"minimax-m3", {65.1685393258427, 75.0, 82.154, 47.1064814814815}, false},
    {"qwen3.6-plus", {61.4232209737828, 73.4, 85.952, std::nullopt}, false},
    {"qwen3.7-max", {74.53183520599251, 68.8, 87.057, 49.537037037037}, false},
    {"qwen3.7-plus",
     {61.0486891385768, std::nullopt, std::nullopt, 46.064814814814795},
     false},
    {"qwen3.8-flash",
     {std::nullopt, std::nullopt, std::nullopt, std::nullopt},
     false},
    {"qwen3.8-max", {81.2734082397004, 85.6, 87.852, 53.2407407407407}, false},
}};

} // namespace zed::app
