#!/usr/bin/env python3
"""Generate the offline model score table from the dated, source-backed snapshot."""

import argparse
import json
import math
from pathlib import Path
import shutil
import subprocess


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "data/model-benchmarks-2026-09-07.json"
OUTPUT = ROOT / "src/app/model_score_data.hpp"
BENCHMARKS = (
    "aa_terminalbench_2_1",
    "vals_swe_verified",
    "vals_livecodebench",
    "aa_scicode",
)


def generate(snapshot):
    assert tuple(b["id"] for b in snapshot["benchmarks"]) == BENCHMARKS
    assert [b["weight"] for b in snapshot["benchmarks"]] == [40, 30, 20, 10]
    seen = set()
    rows = []
    for model in snapshot["models"]:
        model_id = model["id"]
        if model_id in seen:
            raise ValueError(f"Duplicate model ID: {model_id}")
        seen.add(model_id)
        values = []
        for benchmark in BENCHMARKS:
            observation = model["observations"].get(benchmark)
            if observation is None:
                values.append("std::nullopt")
                continue
            value = observation["percent"]
            if not math.isfinite(value) or not 0 <= value <= 100:
                raise ValueError(f"Invalid percentage for {model_id}/{benchmark}")
            values.append(repr(float(value)))
        reference = "true" if model["reference_mapping"] else "false"
        rows.append(
            "    {" + json.dumps(model_id) + ", {" + ", ".join(values)
            + "}, " + reference + "},"
        )
    return "\n".join([
        "// Generated by scripts/generate_model_score_data.py; edit the JSON snapshot.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <optional>",
        "#include <string_view>",
        "",
        "namespace zed::app {",
        "",
        "struct ModelBenchmarkRow {",
        "  std::string_view id;",
        "  std::array<std::optional<double>, 4> percentages;",
        "  bool reference_mapping;",
        "};",
        "",
        f"inline constexpr std::array<ModelBenchmarkRow, {len(rows)}> kModelBenchmarkRows{{{{",
        *rows,
        "}};",
        "",
        "} // namespace zed::app",
        "",
    ])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--clang-format", default=shutil.which("clang-format"))
    args = parser.parse_args()
    if not args.clang_format:
        parser.error("clang-format is required; pass --clang-format /path/to/clang-format")
    content = generate(json.loads(SNAPSHOT.read_text()))
    formatted = subprocess.run(
        [args.clang_format, f"--assume-filename={OUTPUT}"],
        input=content, text=True, capture_output=True, check=True,
    ).stdout
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != formatted:
            raise SystemExit("Model score table is stale; regenerate it from the JSON snapshot.")
        print("Model score table matches the dated snapshot.")
    else:
        OUTPUT.write_text(formatted)
        print(f"Generated {OUTPUT}")


if __name__ == "__main__":
    main()
